services:
  backend-prod:
    build:
      context: ./llm-store-backend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 4000:4000

  ui-prod:
    build:
      context: ./llm-store-ui
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend-prod

  nginx-server:
    build:
      context: ./nginx
      dockerfile : Dockerfile.prod
    ports:
    - "80:80"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend-prod
      - ui-prod
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --nginx --webroot -w /var/www/certbot --force-renewal --email dineshpabbi10@outlook.com -d dineshpabbi.xyz --agree-tos
    depends_on:
      - nginx-server
  